### ISSUE TITLE
Alias: Alias system design and planning

### ISSUE THREAD

**Issue by fcharlie** [M2Team/zsudo#2]
## Alias File

|Key|Type|Details|
|---|---|---|
|Executable|String|Exe(Command) Path, support Expand Environment Value|

**Comment by fcharlie** [comment]
Alias File Template:

*pwsh.app*

```toml
[Description]
Title="App Loader"
Author="Force.Charlie"
Last="20160327"
Level=10

[Base]
Executable="path/to/exe"
Icon="/path/to/app/icon"
StartupDir="/path/to/startupdir"
Path=[
    "/path/to/cmake",
    "/path/to/git"
]
CPUPriority="High"
#Real time
#High
#Above Normal
#Normal
#Below Normal
#Low
Env=[
  "KEY=VALUE",
  "KEY2=VALUE2"
]
Privilege=[
 "SE_INCREASE_QUOTA_NAME"
]
```
